### list cidade
GET http://localhost:3000/clientes

### get cidade
GET http://localhost:3000/clientes/1

### create cidade
POST http://localhost:3000/clientes
Content-Type: application/json

{
    "nome":"Goana",
    "ufId":2
}

### update cidade
PATCH  http://localhost:3000/clientes/1
Content-Type: application/json

{
    "nome":"Goiania"
}
### delete cidade
DELETE http://localhost:3000/clientes/1